version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/cairo

    steps:
      - checkout

      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: tests
          command: py.test

workflows:
  main:
    jobs:
      - build-and-test

