version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default

    working_directory: ~/cairo

    steps:
      - checkout

      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: tests
          command: py.test

workflows:
  main:
    jobs:
      - build-and-test

